version: '3.8'
services:
  streamlit-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - GROQ_API_KEY=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  # Substitua com sua chave API real
    volumes:
      - .:/app
    restart: unless-stopped
